---
# tasks file for single_task_role
- name: Asserts my_own_module
  # hosts: localhost
  tasks:
    - name: Create file with some content
      my_own_namespace.yandex_cloud_elk.my_own_module:
        path: ./test_file_from_playbook.txt
        content: test_file_from_playbook111222333\n